### ISSUE TITLE
Error with MixSIAR in MacYosemite

### ISSUE THREAD

**Issue by LeonardoReyes** [brianstock/MixSIAR#14]
After a bit of an ordeal I managed to install rjags and R2jags to work fine in Yosemite. Now when I call MixSIAR I get this...

  Error in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  invalid multibyte string at '<83>0)'

Is there a way of correcting this???

I am running R 3.0.3

Thanks!

**Comment by brianstock** [comment]
Sorry, I haven't come across that error before.  First, do all of the packages load correctly on your machine?

```
require(ggplot2)
require(gWidgetsRGtk2)
require(R2jags)
require(MASS)
require(RColorBrewer)
require(reshape)
```

The only suggestions I have are the basic ones:
  - Try updating your R to the latest version (3.1.2 currently), then update your packages
  - Google your error message

**Comment by akbreezo** [comment]
Did you ever get a resolution to this problem? I am  having the same issue in Mavericks. I went through a lot of steps and struggles to get the package installed. I am running OS 10.9.5, R 3.1.2 and RStudio 0.98.1102. 
Thanks

**Comment by brianstock** [comment]
No, sorry.  Last week I tried to help someone in person with this same error, but couldn't figure it out.  It's only on Mac (recent installs on Windows and Linux have no problems), and affects both the GUI and script versions.  We tried the advice here to no avail: http://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon.

Will let you know if we get it working, and you do the same!

**Comment by akbreezo** [comment]
Thanks for the prompt reply.  I will definitely let you know if I find a solution. 
I'm also getting the following error during loading of data into the GUI:
(R:2802): Gtk-WARNING **: Attempting to store changes into `/Users/bree/.local/share/recently-used.xbel', but failed: Failed to create file '/Users/bree/.local/share/recently-used.xbel.S7YQUX': No such file or directory

(R:2802): Gtk-WARNING **: Attempting to set the permissions of `/Users/bree/.local/share/recently-used.xbel', but failed: No such file or directory

I've tried the fix here with no luck: http://blog.aguskurniawan.net/post/gtkwarning.aspx

**Comment by brianstock** [comment]
Hi @LeonardoReyes  and @akbreezo,

We've had problems installing on Mac in the past, but are hopeful this issue has been resolved.  Try updating your R and packages, then follow the Mac install instructions in the new manual (v3.0).

Let me know if this works or not!

-Brian

**Comment by kristingleeson** [comment]
Hi @brianstock - are there any other solutions to try for this error? I'm getting the same as @akbreezo where it won't locate the 'recently used' folder. I've tried creating the folder using terminal command, but that hasn't changed anything. I have the latest software, all downloaded just this week. 

Any help would be greatly appreciated so I can use this software on the mac :)

Thanks in advance.

**Comment by kristingleeson** [comment]
I now have everything working on Mac OS X Yosemite 10.10.5 with no problems. The updated version (https://github.com/brianstock/MixSIAR/releases/tag/3.0.2) has fixed the issue. I'm still getting the GTK error, but it all seems to be running ok despite that error popping up in R. Thanks for the help @brianstock - screen shot below of first plot from wolves data up and running:

![screen shot 2015-11-20 at 9 41 04 am](https://cloud.githubusercontent.com/assets/15901388/11288174/3939ed8e-8f6d-11e5-8a57-557f7785d513.png)

**Comment by akbreezo** [comment]
I'm still getting the error and am not able to view the plots. I installed the latest released and updated the packages.
